[package]
name = "json_formatter"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "json_formatter_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.61"
serde_json = "1"
